import os

APP_NAME = "HotelApp"
APP_DIRECTORY = os.getenv('APPDATA') + "\\" + APP_NAME
APP_CONFIG_PATH = APP_DIRECTORY + "\\" + "Config.data"

DATABASE_USER = ""
DATABASE_PASSWORD = ""
DATABASE_HOST = ""
DATABASE_PORT = ""
DATABASE_NAME = ""
